### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by captain-fox** [danielbayley/atom-custom-app-icon#3]

**Comment by Jarada** [comment]
On High Sierra, after changing the App Icon, try the following:

```
touch /Applications/Atom.app
touch /Applications/Atom.app/Contents/Info.plist
killall Dock
```

That should make it appear correctly in your dock.

**Comment by danielbayley** [comment]
@derwustenfuchs This was caused by `NODE_PATH` being altered within Atom. Should be fixed now…Let me know, thanks!
